fragment Link on Link {
  type
  page {
    ... on Document {
      __typename
      _id
      _type

      ... on Page {
        slug {
          ...Slug
        }
      }

      ... on Blog {
        slug {
          ...Slug
        }
      }
    }
  }
  url
  section
  email
  phone
  file {
    ...SanityFile
  }
  newTab
}
