packages:
  - 'frontend'
  - 'frontend-nextjs'
  - 'cms'
  - 'sanity'
  - 'sanity-nextjs'
  - 'shopify'

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAge: 1440
