import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";

const BIZUDMinchoRegular = localFont({
  src: "../../public/fonts/BIZUDMincho-Regular.woff2",
  variable: "--font-bizud-mincho-regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${BIZUDMinchoRegular.variable} bg-background text-foreground h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <main>{children}</main>
      </body>
    </html>
  );
}
