fragment Cart on Cart {
  id
  buyerIdentity {
    countryCode
  }
  checkoutUrl
  discountCodes {
    applicable
    code
  }
  cost {
    totalAmount {
      ...Money
    }
  }
  lines(first: 20) {
    edges {
      node {
        ...CartLine
      }
    }
  }
}

fragment CartLine on CartLine {
  __typename

  id
  quantity
  discountAllocations {
    discountedAmount {
      ...Money
    }
  }
  cost {
    totalAmount {
      ...Money
    }
  }
  merchandise {
    ... on ProductVariant {
      ...MerchandiseFields
    }
  }
}
