fragment ProductPrice on Product {
  variants(first: 16) {
    edges {
      node {
        id
        price {
          amount
        }
        compareAtPrice {
          amount
        }
      }
    }
  }
}
