fragment Product on Product {
  __typename
  _id

  mediaThumbnail {
    ...Media
  }

  mediaGallery {
    ...Media
  }

  meta {
    ...Meta
  }

  shopify {
    title
    handle {
      ...Slug
    }
  }
}
